In [1]:
#일반 라이브러리
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

#API를 사용하기 위한 import
from geoband.API import *
import folium
import json
import geopandas as gpd

files = ['1.5개시도_경찰서_관할경계.geojson',
            '2.5개시도_치안안전센터_관할경계.geojson',
            '3.체감안전도_설문지.txt',
            '4.체감안전도_통계(2017~2019).csv',
            '5.112신고.csv',
            '6.범죄발생원표.csv',
            '7.범죄검거원표.csv',
            '8.범죄피의자원표.csv',
            '9.5개시도_보안등현황.csv',
            '10.5개시도_CCTV설치현황.csv',
            '11.5개시도_교통사고현황.csv',
            '12.경찰서별_지구대별 인원현황.csv',
            '13.5개시도_화재발생통계.csv',
            '14.5개시도_성연령별_총인구분포.csv',
            '15.5개시도_1인가구수.csv',
            '16.5개시도_인구데이터(외국인).csv',
            '17.5개시도_기초수급자현황.csv',
            '18.5개시도_자살율.csv',
            '19.5개시도_최종학력통계.csv',
            '20.5개시도_공원현황.csv',
            '21.5개시도_유흥업소_단란주점현황.csv',
            '22.5개시도_비상벨현황.geojson',
            '23.5개시도_종관관측기상(2017~2020).csv',
            '24.5개시도_도로명주소(건물).geojson',
            '25.결과제출양식.csv',
            '26.코드정의서.xlsx',
            '27.5개시도_설문결과데이터(2017~2018).csv']

data = dict()

for i in range(len(files)):
    file_name = files[i]
    
    #split
    key,name,lang = file_name.split(".")
    
    #GetCompasData('SBJ_2107_004', key, file_name)
    if lang == "csv":
        data[name] = pd.read_csv(file_name)
    elif lang == "geojson":
        data[name] = gpd.read_file(file_name)
    elif lang == "xlsx":
        data[name] = pd.read_excel(file_name)

/opt/app-root/lib/python3.6/site-packages/geopandas/_compat.py:110: UserWarning: The Shapely GEOS version (3.8.0-CAPI-1.13.1 ) is incompatible with the GEOS version PyGEOS was compiled with (3.9.0-CAPI-1.16.2). Conversions between both will be slow.
  shapely_geos_version, geos_capi_version_string
/opt/app-root/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (4,8) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [2]:
data["5개시도_최종학력통계"]
police12 = pd.read_csv("police12.csv")
police12 = police12.iloc[:,1:]
police12 = police12.sort_values("jur_stn")
police12

,jur_stn,year,상반기,파출소수,경찰관수,5대범죄발생건,5대범죄검거건,5대범죄검거율,전체인구,전체성비,...,교통사고발생건,평균출동시간,tot_f_safety,dept_safety,crime_safety,rob_satety_q1,mur_safety_q2,ta_safety_q3,raw_odder_q4,overall_q5
23,마산동부경찰서,2019,1,7,185,1819,396,0.217702,192446,100.3,...,213,365,71.7,71.4,77.2,76.1,78.2,66.4,69.9,72.4
22,마산동부경찰서,2019,0,7,185,1819,455,0.250137,192446,100.3,...,243,365,71.9,71.4,75.8,75.0,76.5,69.4,68.9,73.1
21,마산동부경찰서,2018,1,7,185,2021,411,0.203365,197683,100.8,...,203,359,72.1,71.9,77.5,76.0,79.0,67.5,70.0,72.6
20,마산동부경찰서,2018,0,7,185,2021,428,0.211776,197683,100.8,...,186,359,71.2,71.0,74.0,72.4,75.6,67.9,70.7,71.8
19,마산동부경찰서,2017,1,7,185,2025,412,0.203457,202864,100.9,...,165,370,69.5,68.8,75.8,74.6,77.0,64.0,65.7,71.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49,창원중부경찰서,2017,1,6,201,1205,582,0.482988,226726,109.0,...,323,370,68.7,67.8,76.4,76.0,76.8,63.7,62.4,70.8
50,창원중부경찰서,2018,0,6,201,1259,604,0.479746,225894,108.8,...,349,359,72.6,71.9,76.7,75.7,77.7,67.8,70.6,74.2
51,창원중부경찰서,2018,1,6,201,1196,621,0.519231,225894,108.8,...,338,359,71.8,71.3,79.1,78.0,80.1,65.3,68.6,72.9
52,창원중부경찰서,2019,0,6,201,867,661,0.762399,219951,108.6,...,337,365,74.4,74.5,78.6,77.6,79.6,70.9,73.6,74.1
53,창원중부경찰서,2019,1,6,201,1278,647,0.506260,219951,108.6,...,315,365,75.5,75.2,81.8,80.8,82.8,69.4,73.8,76.1

In [3]:
df = pd.read_csv("police12.csv")
df = df.iloc[:,1:]
df = df.sort_values("jur_stn")
df.columns.tolist()

['jur_stn',
 'year',
 '상반기',
 '파출소수',
 '경찰관수',
 '5대범죄발생건',
 '5대범죄검거건',
 '5대범죄검거율',
 '전체인구',
 '전체성비',
 '0대 비율',
 '10대 비율',
 '20대 비율',
 '30대 비율',
 '40대 비율',
 '50대 비율',
 '60대 비율',
 '외국인수',
 '외국인비율',
 '계',
 '초등학교',
 '중학교',
 '고등학교',
 '대학교(2,3년제)',
 '대학교(4년제 이상)',
 '대학원(석박사 과정)',
 '받지 않았음(미취학 포함)',
 '1인당 담당인구수',
 '기초생활자수',
 '지방세징수액',
 '1인가구비율',
 '절폭신고비율',
 '강살신고비율',
 '교통신고비율',
 '질서신고비율',
 '교통사고발생건',
 '평균출동시간',
 'tot_f_safety',
 'dept_safety',
 'crime_safety',
 ' rob_satety_q1',
 'mur_safety_q2',
 'ta_safety_q3',
 'raw_odder_q4',
 'overall_q5']

# 2020년 데이터 따로 만들기

In [4]:
df_2020 = pd.DataFrame(index = range(0), columns= df.columns)

In [5]:
# jur_stn
df_2020["jur_stn"] = df["jur_stn"].unique()

In [6]:
# year
df_2020["year"] = 2020

In [7]:
# 상반기
df_2020["상반기"] = 1
df_2020.head()
df_2020 = df_2020.sort_values("jur_stn")
df_2020.head()

,jur_stn,year,상반기,파출소수,경찰관수,5대범죄발생건,5대범죄검거건,5대범죄검거율,전체인구,전체성비,...,교통사고발생건,평균출동시간,tot_f_safety,dept_safety,crime_safety,rob_satety_q1,mur_safety_q2,ta_safety_q3,raw_odder_q4,overall_q5
0,마산동부경찰서,2020,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,마산중부경찰서,2020,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,서울강남경찰서,2020,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,서울강동경찰서,2020,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,서울강북경찰서,2020,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# 파출소수
temp = df.groupby("jur_stn")["파출소수"].mean().reset_index()
df_2020["파출소수"] = temp.sort_values("jur_stn")["파출소수"].tolist()
df_2020.head()

,jur_stn,year,상반기,파출소수,경찰관수,5대범죄발생건,5대범죄검거건,5대범죄검거율,전체인구,전체성비,...,교통사고발생건,평균출동시간,tot_f_safety,dept_safety,crime_safety,rob_satety_q1,mur_safety_q2,ta_safety_q3,raw_odder_q4,overall_q5
0,마산동부경찰서,2020,1,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,마산중부경찰서,2020,1,8,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,서울강남경찰서,2020,1,8,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,서울강동경찰서,2020,1,9,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,서울강북경찰서,2020,1,9,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# 경찰관수
temp = df.groupby("jur_stn")["경찰관수"].mean().reset_index()
df_2020["경찰관수"] = temp.sort_values("jur_stn")["경찰관수"]
df_2020.head()

,jur_stn,year,상반기,파출소수,경찰관수,5대범죄발생건,5대범죄검거건,5대범죄검거율,전체인구,전체성비,...,교통사고발생건,평균출동시간,tot_f_safety,dept_safety,crime_safety,rob_satety_q1,mur_safety_q2,ta_safety_q3,raw_odder_q4,overall_q5
0,마산동부경찰서,2020,1,7,185,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,마산중부경찰서,2020,1,8,142,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,서울강남경찰서,2020,1,8,421,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,서울강동경찰서,2020,1,9,393,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,서울강북경찰서,2020,1,9,347,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# 5대 범죄발생건 --> 2020년 데이터 누락

df = data["범죄발생원표"]
df = data["범죄발생원표"]
df["jur_stn"] = df["jur_stn"].str.lstrip()

df["year"] = ""
df["상반기"] = ""

df.crm_date = df.crm_date.astype("str")
temp = df.crm_date.str.split("/")

length = list(map(lambda x: len(x),temp))
date_list = temp.tolist()

# year를 구분하고, 상반기 하반기를 구분함
for idx, l in enumerate(length):
    if l == 1:
        year = date_list[idx][0][:4]
        flag = int(date_list[idx][0][4:6] <= "06")
    else:
        year = date_list[idx][-1]
        flag = int(date_list[idx][0] <= "06")
    
    # 넣기
    temp = [year,flag]
    df.iloc[idx,-2:] = temp

In [11]:
# 5대 범죄검거건 --> 2020년 데이터 누락
df = data["범죄검거원표"]

df["date"] =df["date"].astype("str")

df["year"] = df.date.str[:4]
df["상반기"] = (df.date.str[4:] <= "06").astype("int")
df.head()

     date    jur_stn            crm  year  상반기
0  201701  경남마산중부경찰서             사기  2017    1
1  201701  경남마산중부경찰서       경범죄처벌법위반  2017    1
2  201612  경남마산중부경찰서  도로교통법위반(음주운전)  2016    0
3  201702  경남마산중부경찰서       위계공무집행방해  2017    1
4  201702  경남마산중부경찰서       위계공무집행방해  2017    1

In [12]:
# 5대 범죄검거율 --> 5대범죄 검거/5대범죄 발생 (비율)

In [13]:
# 전체인구,전체성비', '0대 비율', '10대 비율', '20대 비율', '30대 비율','40대 비율', '50대 비율', '60대 비율
--> 데이터 누락 --> 회귀분석도 좋지만, 평균값 취해도 좋을 것 같다.

df = data["5개시도_성연령별_총인구분포"]
df.head()

SyntaxError: invalid syntax (<ipython-input-13-b37cf7be57da>, line 2)

In [14]:
# 외국인 --> 2020년데이터 누락
df = data["5개시도_인구데이터(외국인)"]
df.head()

,sido,sgg,foreigner_all(2017),foreigner_M(2017),foreigner_F(2017),foreigner_all(2018),foreigner_M(2018),foreigner_F(2018),foreigner_all(2019),foreigner_M(2019),foreigner_F(2019)
0,서울특별시,종로구,10979,4913,6066,12056,5536,6520,13159,5818,7341
1,서울특별시,중구,10265,4804,5461,11988,5735,6253,12559,6025,6534
2,서울특별시,용산구,16005,8712,7293,19126,10879,8247,20503,11621,8882
3,서울특별시,성동구,10436,5042,5394,11307,5403,5904,11774,5610,6164
4,서울특별시,광진구,18399,8323,10076,19729,9032,10697,20925,9474,11451

In [15]:
# '계', '초등학교', '중학교', '고등학교', '대학교(2,3년제)', '대학교(4년제 이상)', '대학원(석박사 과정)', '받지 않았음(미취학 포함)'
temp = police12.drop_duplicates("jur_stn", keep = "first")[['계', '초등학교', '중학교','고등학교', '대학교(2,3년제)', '대학교(4년제 이상)', '대학원(석박사 과정)', '받지 않았음(미취학 포함)']]
temp.index = range(0,41)
df_2020[['계', '초등학교', '중학교', '고등학교', '대학교(2,3년제)', '대학교(4년제 이상)', '대학원(석박사 과정)', '받지 않았음(미취학 포함)']] = temp

In [16]:
df_2020[['계', '초등학교', '중학교', '고등학교', '대학교(2,3년제)', '대학교(4년제 이상)', '대학원(석박사 과정)', '받지 않았음(미취학 포함)']]

,계,초등학교,중학교,고등학교,"대학교(2,3년제)",대학교(4년제 이상),대학원(석박사 과정),받지 않았음(미취학 포함)
0,195344,0.127329,0.123065,0.352491,0.146675,0.196853,0.023671,0.029916
1,104775,0.139012,0.119265,0.326423,0.117872,0.228681,0.026791,0.041957
2,491494,0.075476,0.057791,0.187732,0.082434,0.434410,0.149117,0.013040
3,415370,0.102429,0.091422,0.305383,0.124503,0.302675,0.054017,0.019571
4,301584,0.133833,0.119771,0.348676,0.125594,0.213552,0.031951,0.026623
5,530869,0.103924,0.089033,0.302796,0.134717,0.299172,0.049570,0.020789
6,542386,0.100869,0.087331,0.272452,0.128305,0.324677,0.066442,0.019925
7,335188,0.099073,0.088389,0.288790,0.119945,0.322321,0.063800,0.017683
8,381097,0.114635,0.098169,0.300202,0.139723,0.278879,0.046907,0.021485
9,215450,0.118928,0.119336,0.354115,0.132226,0.219494,0.030072,0.025830
10,112574,0.107289,0.103336,0.299678,0.104118,0.295752,0.064029,0.025796
11,531568,0.115152,0.096469,0.284600,0.119328,0.311232,0.050919,0.022300
12,321886,0.113668,0.100778,0.337526,0.124156,0.264510,0.037495,0.021868
13,333788,0.116379,0.104677,0.304319,0.109908,0.287590,0.052779,0.024348
14,373421,0.095562,0.076131,0.245361,0.112573,0.372614,0.079875,0.017883
15,350468,0.106549,0.076404,0.243765,0.106897,0.361360,0.086099,0.018926
16,389692,0.081998,0.054843,0.164299,0.076958,0.438662,0.169329,0.013911
17,284679,0.107774,0.092002,0.269170,0.108090,0.328208,0.072847,0.021909
18,448553,0.114368,0.095306,0.323850,0.123840,0.272904,0.045767,0.023964
19,389692,0.081998,0.054843,0.164299,0.076958,0.438662,0.169329,0.013911
20,270022,0.107680,0.096081,0.272185,0.113054,0.313430,0.076416,0.021154
21,434577,0.120439,0.099752,0.278906,0.108492,0.305617,0.064723,0.022072
22,591252,0.093067,0.070606,0.241778,0.107284,0.372939,0.097503,0.016822
23,491494,0.075476,0.057791,0.187732,0.082434,0.434410,0.149117,0.013040
24,438004,0.112513,0.093798,0.274765,0.114115,0.317810,0.067826,0.019173
25,338321,0.104587,0.086619,0.257974,0.114560,0.340428,0.077873,0.017959
26,201237,0.102710,0.082306,0.256856,0.099336,0.337408,0.099505,0.021880
27,448553,0.114368,0.095306,0.323850,0.123840,0.272904,0.045767,0.023964
28,140506,0.105291,0.096700,0.257441,0.089655,0.327210,0.101156,0.022547
29,434577,0.120439,0.099752,0.278906,0.108492,0.305617,0.064723,0.022072
30,377939,0.121379,0.121869,0.362543,0.128034,0.212936,0.029769,0.023469
31,112574,0.107289,0.103336,0.299678,0.104118,0.295752,0.064029,0.025796
32,140506,0.105291,0.096700,0.257441,0.089655,0.327210,0.101156,0.022547
33,182967,0.159663,0.085256,0.221357,0.112261,0.297748,0.085065,0.038652
34,348781,0.110760,0.086358,0.309598,0.128393,0.285944,0.056419,0.022521
35,348781,0.110760,0.086358,0.309598,0.128393,0.285944,0.056419,0.022521
36,348781,0.110760,0.086358,0.309598,0.128393,0.285944,0.056419,0.022521
37,239657,0.150457,0.112828,0.268112,0.115482,0.267390,0.042778,0.042953
38,141133,0.137983,0.112624,0.340409,0.149504,0.203503,0.026670,0.029306
39,205920,0.101491,0.102171,0.367099,0.144041,0.239797,0.024102,0.021300
40,192893,0.095898,0.083507,0.327435,0.145319,0.285583,0.044761,0.017497

In [17]:
df_2020.isnull().sum()

jur_stn            0
year               0
상반기                0
파출소수               0
경찰관수               0
5대범죄발생건           41
5대범죄검거건           41
5대범죄검거율           41
전체인구              41
전체성비              41
0대 비율             41
10대 비율            41
20대 비율            41
30대 비율            41
40대 비율            41
50대 비율            41
60대 비율            41
외국인수              41
외국인비율             41
계                  0
초등학교               0
중학교                0
고등학교               0
대학교(2,3년제)         0
대학교(4년제 이상)        0
대학원(석박사 과정)        0
받지 않았음(미취학 포함)     0
1인당 담당인구수         41
기초생활자수            41
지방세징수액            41
1인가구비율            41
절폭신고비율            41
강살신고비율            41
교통신고비율            41
질서신고비율            41
교통사고발생건           41
평균출동시간            41
tot_f_safety      41
dept_safety       41
crime_safety      41
 rob_satety_q1    41
mur_safety_q2     41
ta_safety_q3      41
raw_odder_q4      41
overall_q5        41
dtype: int64

In [18]:
## 기초수급자수 ## --> 어차피 전체 인구데이터가 필요해서 예측하거나 분석하는게 나을듯

df = data["5개시도_기초수급자현황"]
df.sgg_nm.unique().tolist()
df.date = df.date.astype("str")
df["상반기"] = (df.date.str[4:] <= "06").astype("int")
df["year"] = df.date.str[:4]

In [19]:
# 지방세징수액 --> 아직 해당자료가 없음.
police12["지방세징수액"]

23    266274
22    266274
21    251555
20    251555
19    279864
       ...
49    279864
50    251555
51    251555
52    266274
53    266274
Name: 지방세징수액, Length: 246, dtype: int64

In [20]:
# 지방세징수액 --> 아직 해당자료가 없음.
police12["지방세징수액"]

23    266274
22    266274
21    251555
20    251555
19    279864
       ...
49    279864
50    251555
51    251555
52    266274
53    266274
Name: 지방세징수액, Length: 246, dtype: int64

In [21]:
# 1인가구비율
sgg_list = ["종로구"
            ,"중구"
            ,"용산구"
            ,"성동구"
            ,"광진구"
            ,"동대문구"
            ,"중랑구"
            ,"성북구"
            ,"강북구"
            ,"도봉구"
            ,"노원구"
            ,"은평구"
            ,"서대문구"
            ,"마포구"
            ,"양천구"
            ,"강서구"
            ,"구로구"
            ,"금천구"
            ,"영등포구"
            ,"동작구"
            ,"관악구"
            ,"서초구"
            ,"강남구"
            ,"송파구"
            ,"강동구"
            ,"세종특별자치시"
            ,"수원시"
            ,"진주시"
            ,"창원시"]

In [22]:
family1 = [0.40973602,0.414172399,0.385325031,0.348526018,0.409632454
            ,0.405159171,0.34341026 ,0.342368919 ,0.351951003 ,0.273896453 ,0.278438047
            ,0.303481595 ,0.374594327 ,0.393151648 ,0.237503312 ,0.353023593 ,0.310641566
            ,0.409293062 ,0.394110511 ,0.382085762 ,0.519093505 ,0.281457569 ,0.330402762
            ,0.288130557 ,0.284033689 ,0.313264705 ,0.314472129 ,0.336369835, 0.290857921]
family1 = pd.DataFrame(family1)
family1["jur_stn"] = sgg_list
family1["year"] = 2020
family1 = family1.rename(columns= {0:"1인가구비율"})
family1.head()

     1인가구비율 jur_stn  year
0  0.409736     종로구  2020
1  0.414172      중구  2020
2  0.385325     용산구  2020
3  0.348526     성동구  2020
4  0.409632     광진구  2020

In [23]:
dong_police2 = {"중구":["서울중부경찰서","서울남대문경찰서"],
             "강서구": ["서울강서경찰서"],
             "종로구": ["서울종로경찰서","서울혜화경찰서"],
             "용산구": ["서울용산경찰서"],
             "성동구":["서울성동경찰서"],
             "광진구":["서울광진경찰서"],
             "동대문구":["서울동대문경찰서"],
             "중랑구":["서울중랑경찰서"],
             "성북구":["서울성북경찰서","서울종암경찰서"],
             "강북구":["서울강북경찰서"],
             "도봉구":["서울도봉경찰서"],
             "노원구":["서울노원경찰서"],
             "은평구":["서울은평경찰서","서울서부경찰서"],
             "서대문구":["서울서대문경찰서"],
             "마포구":["서울마포경찰서"],
             "양천구":["서울양천경찰서"],
             "구로구":["서울구로경찰서"],
             "금천구":["서울금천경찰서"],
             "영등포구":["서울영등포경찰서"],
             "동작구":["서울동작경찰서"],
             "관악구":["서울관악경찰서"],
             "서초구":["서울서초경찰서","서울방배경찰서"],
             "강남구":["서울강남경찰서","서울수서경찰서"],
             "송파구":["서울송파경찰서"],
             "강동구":["서울강동경찰서"],
             "세종특별자치시":["세종경찰서"],
             "진주시":["진주경찰서"],
             "창원시":["창원서부경찰서","창원중부경찰서","마산중부경찰서","마산동부경찰서","진해경찰서"],
              "수원시":["수원남부경찰서","수원서부경찰서","수원중부경찰서"]}


dong = ['강남구',
         '강동구',
         '강북구',
         '강서구',
         '관악구',
         '광진구',
         '구로구',
         '금천구',
         '노원구',
         '도봉구',
         '동대문구',
         '동작구',
         '마포구',
         '서대문구',
         '서초구',
         '성동구',
         '성북구',
         '세종특별자치시',
         '송파구',
         '수원시',
         '양천구',
         '영등포구',
         '용산구',
         '은평구',
         '종로구',
         '중구',
         '중랑구',
         '진주시',
         '창원시']

In [24]:
df_basic = family1
Basic = pd.DataFrame(index = range(0,0), columns = family1.columns)
for sgg in dong: # dong정보는 위에서 가져옴
    police_list = dong_police2[sgg] #위에서 나옴
    temp = df_basic.loc[df_basic["jur_stn"] == sgg,:] 
        
    if len(police_list) == 1:
        temp["jur_stn"] = police_list[0]
        Basic = pd.concat([Basic,temp])
    else:
        for policer in police_list:
            temp["1인가구비율"] = (temp["1인가구비율"] /len(police_list)).astype("float")
            temp["jur_stn"] = policer
            Basic = pd.concat([Basic,temp])
            temp = df_basic.loc[df_basic["jur_stn"] == sgg,:]

/opt/app-root/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/opt/app-root/lib/python3.6/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/opt/app-root/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [25]:
Basic = Basic.sort_values("jur_stn")
Basic.index = range(41)

In [26]:
df_2020["1인가구비율"] = Basic["1인가구비율"]

# 112 신고데이터

In [27]:
df_2020.isnull().sum()

jur_stn            0
year               0
상반기                0
파출소수               0
경찰관수               0
5대범죄발생건           41
5대범죄검거건           41
5대범죄검거율           41
전체인구              41
전체성비              41
0대 비율             41
10대 비율            41
20대 비율            41
30대 비율            41
40대 비율            41
50대 비율            41
60대 비율            41
외국인수              41
외국인비율             41
계                  0
초등학교               0
중학교                0
고등학교               0
대학교(2,3년제)         0
대학교(4년제 이상)        0
대학원(석박사 과정)        0
받지 않았음(미취학 포함)     0
1인당 담당인구수         41
기초생활자수            41
지방세징수액            41
1인가구비율             0
절폭신고비율            41
강살신고비율            41
교통신고비율            41
질서신고비율            41
교통사고발생건           41
평균출동시간            41
tot_f_safety      41
dept_safety       41
crime_safety      41
 rob_satety_q1    41
mur_safety_q2     41
ta_safety_q3      41
raw_odder_q4      41
overall_q5        41
dtype: int64

In [28]:
df = data["112신고"]
df.date = df.date.astype("str")
df["year"] = df.date.str[:4]
temp = df.date.str[4:6] <= "06"
df["상반기"] = temp.astype("int")
df = df.drop("date", axis = 1)
df.head()

  jur_stn report_sx    inc_info  year  상반기
0    서울서부        남성        분실습득  2018    1
1    서울송파        여성          폭력  2018    1
2    서울강서        남성          소음  2018    1
3   서울영등포        여성  실종(실종아동 등)  2018    1
4    서울강서        남성        상담문의  2018    1

In [29]:
df[(df["jur_stn"] == "세종") & (df["year"] == "2019")]

        jur_stn report_sx inc_info  year  상반기
7517139      세종        남성     위험방지  2019    1
7517140      세종        남성     위험방지  2019    1
7517141      세종        남성     행패소란  2019    1
7517142      세종        남성     위험방지  2019    1
7517143      세종        남성     상담문의  2019    1
...         ...       ...      ...   ...  ...
7538412      세종        남성    기타형사범  2019    1
7538413      세종        남성     교통위반  2019    1
7538414      세종        불상     상담문의  2019    1
7538415      세종        여성     교통사고  2019    1
7538416      세종        남성     교통불편  2019    1

[21278 rows x 5 columns]

In [30]:
def count_case(crimes):
    df_violence = df[df["inc_info"].isin(crimes)]
    sgg_list = df_violence["jur_stn"].unique().tolist()
    ans = pd.DataFrame(index = range(0,0), columns= ["year","상반기","jur_stn","city"])

    for sgg in sgg_list:
        temp = df_violence[df_violence["jur_stn"] == sgg]
        df1 = temp.groupby(["year","상반기"])["jur_stn"].count().reset_index()
        df1["city"] = sgg
        ans = pd.concat([ans,df1])

    # 이름바꾸기    
    ans.rename(columns = {"jur_stn": "cnt"}, inplace = True)
    return ans

def print_case():
    case = df["inc_info"].unique()
    case = case.tolist()
    for idx, crim in enumerate(case):
        print(idx+1,crim, end = " ")
        if (idx+1) % 7 == 0:
            print("\n")
            
# 원하는사건/전체사건 비율 구하기
def make_proportion(df1):
    city_list = df1["city"].unique().tolist()
    years = ["2018","2019","2020","2021"]
    half = [0,1]

    for city in city_list:
        for year in years:
            for quarter in half:

                try: 
                    value = total_112[(city,year,quarter)]
                    df2 = df1[(df1["city"] == city) & (df1["상반기"] == quarter) & (df1["year"] == year)]
                    proportion = df2["cnt"] / value
                    df1.loc[(df1["city"] == city) & (df1["상반기"] == quarter) & (df1["year"] == year), "cnt"] = proportion
                    #print(df1[(df1["city"] == city) & (df1["year"] == year)])

                except:
                    pass
                    #print("Fail: {}, {}".format(city,year))
    df1 = df1.astype({"cnt":"float"})
    return df1

#18,19년으로 바꾸기 + city이름 바꾸기
def chagne2police(df):
    df = df[df["year"].isin(["2020"])]
    df.city = df.city.str[:] + "경찰서"
    df = df.rename(columns = {"city":"jur_stn"})
    df = df.astype({"year":"int",
                      "상반기":"int"})
    return df

In [31]:
# 전체 사건개수
total_112 = dict(df.groupby(["jur_stn","year","상반기"])["inc_info"].count())

# 절도폭력
df1 = count_case(["절도","폭력","학교폭력","성폭력","가정폭력","데이트폭력","아동학대(가정내)","아동학대(기타)"])
df1 = make_proportion(df1)
df1 = chagne2police(df1)

# 강도살인
# 강제적인 느낌을 담기면 모두 넣자
df2 = count_case(["강도","살인","납치감금","변사자"])
df2 = make_proportion(df2)
df2 = chagne2police(df2)

# 교통사고
df3 = count_case(["교통사고","교통위반","교통불편","인피도주"])
df3 = make_proportion(df3)
df3 = chagne2police(df3)

# 기초질서/집회시위질서
# 도박추가, 기타경범 추가, 주거침입
df4 = count_case(["소음","행패소란","위험방지","주취자","도박","재물손괴","청소년비행","시비","기타경범","무전취식승차","가출 등","수배불심자","풍속영업","주거침입","스토킹","노점상","위험동물"])
df4 = make_proportion(df4)
df4 = chagne2police(df4)

/opt/app-root/lib/python3.6/site-packages/pandas/core/generic.py:5170: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [32]:
df1 = df1.rename(columns = {"cnt":"절폭신고비율"})
df2 = df2.rename(columns = {"cnt":"강살신고비율"})
df3 = df3.rename(columns = {"cnt":"교통신고비율"})
df4 = df4.rename(columns = {"cnt":"질서신고비율"})
column_list = ["절폭신고비율", "강살신고비율", "교통신고비율", "질서신고비율"]
df4.head()

   year  상반기    질서신고비율  jur_stn
4  2020    0  0.295605  서울강서경찰서
5  2020    1  0.294299  서울강서경찰서
4  2020    0  0.276423  서울중랑경찰서
5  2020    1  0.278161  서울중랑경찰서
4  2020    0  0.309147  서울금천경찰서

In [33]:
temp = pd.merge(df1,df2, how = "inner", on = ["year","상반기","jur_stn"])
temp = pd.merge(temp,df3, how = "inner", on = ["year","상반기","jur_stn"])
temp = pd.merge(temp,df4, how = "inner", on = ["year","상반기","jur_stn"])
temp

    year  상반기    절폭신고비율  jur_stn    강살신고비율    교통신고비율    질서신고비율
0   2020    0  0.078883  서울송파경찰서  0.001983  0.108063  0.292003
1   2020    1  0.090424  서울송파경찰서  0.001967  0.109576  0.284305
2   2020    0  0.089778  서울중랑경찰서  0.005299  0.070842  0.276423
3   2020    1  0.105765  서울중랑경찰서  0.005402  0.075705  0.278161
4   2020    0  0.102407  서울강북경찰서  0.001225  0.073812  0.290799
..   ...  ...       ...      ...       ...       ...       ...
75  2020    1  0.095574    진해경찰서  0.002819  0.122413  0.347336
76  2020    0  0.082539  마산동부경찰서  0.002789  0.141769  0.331988
77  2020    1  0.088938  마산동부경찰서  0.002351  0.134866  0.349179
78  2020    0  0.085631  마산중부경찰서  0.003848  0.137951  0.369515
79  2020    1  0.079057  마산중부경찰서  0.002441  0.121831  0.373037

[80 rows x 7 columns]

# 세종경찰서의 2020년 데이터는 현재 없는 것으로 파악된다.

In [34]:
new_2020 = pd.concat([df_2020,df_2020]).sort_values("jur_stn")
new_2020.index = range(82)

In [35]:
for column in column_list:
    t = temp[column].tolist()
    t.insert(66,np.nan)
    t.insert(66,np.nan)
    new_2020[column] = t

In [36]:
new_2020.isnull().sum()

jur_stn            0
year               0
상반기                0
파출소수               0
경찰관수               0
5대범죄발생건           82
5대범죄검거건           82
5대범죄검거율           82
전체인구              82
전체성비              82
0대 비율             82
10대 비율            82
20대 비율            82
30대 비율            82
40대 비율            82
50대 비율            82
60대 비율            82
외국인수              82
외국인비율             82
계                  0
초등학교               0
중학교                0
고등학교               0
대학교(2,3년제)         0
대학교(4년제 이상)        0
대학원(석박사 과정)        0
받지 않았음(미취학 포함)     0
1인당 담당인구수         82
기초생활자수            82
지방세징수액            82
1인가구비율             0
절폭신고비율             2
강살신고비율             2
교통신고비율             2
질서신고비율             2
교통사고발생건           82
평균출동시간            82
tot_f_safety      82
dept_safety       82
crime_safety      82
 rob_satety_q1    82
mur_safety_q2     82
ta_safety_q3      82
raw_odder_q4      82
overall_q5        82
dtype: int64

# 교통사고발생건

In [37]:
# 상반기 정리
new_2020["상반기"] = [0,1]*41
new_2020

,jur_stn,year,상반기,파출소수,경찰관수,5대범죄발생건,5대범죄검거건,5대범죄검거율,전체인구,전체성비,...,교통사고발생건,평균출동시간,tot_f_safety,dept_safety,crime_safety,rob_satety_q1,mur_safety_q2,ta_safety_q3,raw_odder_q4,overall_q5
0,마산동부경찰서,2020,0,7,185,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,마산동부경찰서,2020,1,7,185,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,마산중부경찰서,2020,0,8,142,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,마산중부경찰서,2020,1,8,142,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,서울강남경찰서,2020,0,8,421,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,진해경찰서,2020,1,6,137,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,창원서부경찰서,2020,0,6,155,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,창원서부경찰서,2020,1,6,155,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,창원중부경찰서,2020,0,6,201,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,창원중부경찰서,2020,1,6,201,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
df = pd.read_csv("11.5개시도_교통사고현황.csv")
# date 전처리
df["date"] = df["date"].str.rstrip("월")

# year
df["year"] = df["date"].str[:4] 

# 상반기
temp = df["date"].str[6:].replace(["1","2","3","4","5","6","7","8","9"],["01","02","03","04","05","06","07","08","09"], inplace= False)
df["상반기"] = (temp.str[:] <= "06").astype("int")

# 교통사고 발생건수
traffic = df.groupby(["jur_stn","year","상반기"]).count().reset_index()

# 마지막 전처리
traffic["jur_stn"] = traffic["jur_stn"].str[:] + "경찰서"
traffic = traffic.iloc[:,:4]
traffic = traffic.rename(columns = {"date":"교통사고발생건"})
traffic = traffic.astype({"year":"int"})
traffic["jur_stn"] = traffic["jur_stn"].str[:].replace("진해경찰서경찰서", "진해경찰서")
traffic = traffic[traffic["year"].isin([2020])]

print(traffic.shape)
traffic.index= range(82)
traffic.head()

(82, 4)

   jur_stn  year  상반기  교통사고발생건
0  마산동부경찰서  2020    0      176
1  마산동부경찰서  2020    1      206
2  마산중부경찰서  2020    0      275
3  마산중부경찰서  2020    1      302
4  서울강남경찰서  2020    0     1120

In [39]:
new_2020["교통사고발생건"] = traffic["교통사고발생건"]

In [40]:
new_2020

,jur_stn,year,상반기,파출소수,경찰관수,5대범죄발생건,5대범죄검거건,5대범죄검거율,전체인구,전체성비,...,교통사고발생건,평균출동시간,tot_f_safety,dept_safety,crime_safety,rob_satety_q1,mur_safety_q2,ta_safety_q3,raw_odder_q4,overall_q5
0,마산동부경찰서,2020,0,7,185,NaN,NaN,NaN,NaN,NaN,...,176,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,마산동부경찰서,2020,1,7,185,NaN,NaN,NaN,NaN,NaN,...,206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,마산중부경찰서,2020,0,8,142,NaN,NaN,NaN,NaN,NaN,...,275,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,마산중부경찰서,2020,1,8,142,NaN,NaN,NaN,NaN,NaN,...,302,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,서울강남경찰서,2020,0,8,421,NaN,NaN,NaN,NaN,NaN,...,1120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,진해경찰서,2020,1,6,137,NaN,NaN,NaN,NaN,NaN,...,366,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,창원서부경찰서,2020,0,6,155,NaN,NaN,NaN,NaN,NaN,...,311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,창원서부경찰서,2020,1,6,155,NaN,NaN,NaN,NaN,NaN,...,340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,창원중부경찰서,2020,0,6,201,NaN,NaN,NaN,NaN,NaN,...,281,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,창원중부경찰서,2020,1,6,201,NaN,NaN,NaN,NaN,NaN,...,274,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 신속출동시간

In [41]:
action = [323]*2*2 # 마산 2개
action += [256]*2*31 # 서울 31개
action += [376]*2 #세종
action += [340]*2*3#수원
action += [323]*2*4 # 진주/진해/창원서부/창원중부

new_2020["평균출동시간"] = action

# 여기까지가 2020년 데이터 총정리
# 이제부터 결측치를 평균값으로 채우자.

In [42]:
columns = ["5대범죄발생건","5대범죄검거건","5대범죄검거율","전체인구","전체성비","0대 비율","10대 비율","20대 비율","30대 비율","40대 비율","50대 비율","60대 비율","외국인수","외국인비율","1인당 담당인구수","기초생활자수","지방세징수액"]

t = police12.groupby(["jur_stn"])["5대범죄발생건","5대범죄검거건","5대범죄검거율","전체인구","전체성비","0대 비율","10대 비율","20대 비율","30대 비율","40대 비율","50대 비율","60대 비율","외국인수","외국인비율","1인당 담당인구수","기초생활자수","지방세징수액"].mean().reset_index()

t2 = pd.concat([t,t], axis = 0).sort_values("jur_stn")
t2.index = range(82)
t2 = t2.drop("jur_stn", axis =1)
t2.head()

/opt/app-root/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  This is separate from the ipykernel package so we can avoid doing imports until

,5대범죄발생건,5대범죄검거건,5대범죄검거율,전체인구,전체성비,0대 비율,10대 비율,20대 비율,30대 비율,40대 비율,50대 비율,60대 비율,외국인수,외국인비율,1인당 담당인구수,기초생활자수,지방세징수액
0,1955.000000,419.500000,0.215229,197664.333333,100.666667,0.077517,0.100247,0.120262,0.127728,0.163603,0.180057,0.230551,2803.666667,0.014195,1068.000000,0.137921,2.658977e+05
1,1955.000000,419.500000,0.215229,197664.333333,100.666667,0.077517,0.100247,0.120262,0.127728,0.163603,0.180057,0.230551,2803.666667,0.014195,1068.000000,0.137921,2.658977e+05
2,1346.666667,337.333333,0.251680,178253.666667,99.866667,0.076680,0.086386,0.117539,0.131787,0.144838,0.169876,0.272831,2867.000000,0.016087,1254.666667,0.152239,2.658977e+05
3,1346.666667,337.333333,0.251680,178253.666667,99.866667,0.076680,0.086386,0.117539,0.131787,0.144838,0.169876,0.272831,2867.000000,0.016087,1254.666667,0.152239,2.658977e+05
4,2211.166667,934.333333,0.430306,256587.000000,92.100000,0.072266,0.108036,0.135584,0.162955,0.183411,0.151106,0.186564,4365.333333,0.017034,609.000000,0.114617,1.581083e+06

In [43]:
# 평균값 assign
new_2020[columns] = t2

In [44]:
new_2020.isnull().sum()

jur_stn            0
year               0
상반기                0
파출소수               0
경찰관수               0
5대범죄발생건            0
5대범죄검거건            0
5대범죄검거율            0
전체인구               0
전체성비               0
0대 비율              0
10대 비율             0
20대 비율             0
30대 비율             0
40대 비율             0
50대 비율             0
60대 비율             0
외국인수               0
외국인비율              0
계                  0
초등학교               0
중학교                0
고등학교               0
대학교(2,3년제)         0
대학교(4년제 이상)        0
대학원(석박사 과정)        0
받지 않았음(미취학 포함)     0
1인당 담당인구수          0
기초생활자수             0
지방세징수액             0
1인가구비율             0
절폭신고비율             2
강살신고비율             2
교통신고비율             2
질서신고비율             2
교통사고발생건            0
평균출동시간             0
tot_f_safety      82
dept_safety       82
crime_safety      82
 rob_satety_q1    82
mur_safety_q2     82
ta_safety_q3      82
raw_odder_q4      82
overall_q5        82
dtype: int64

# 남은 결측치
세종시에 대한 신고비율(절폭/강살/교통/질서)
--> 회귀분석 진행

In [45]:
column_list

['절폭신고비율', '강살신고비율', '교통신고비율', '질서신고비율']

In [48]:
target = "절폭신고비율"

dataset1 = police12.iloc[:,3:-8]
dataset2 = new_2020.iloc[:,3:-8]

train, test = dataset1[dataset1[target].isnull() == False], dataset2[dataset2[target].isnull()]
X_train, Y_train = train.drop(column_list, axis = 1), train[target]

# 변수제거
X_test = test.drop(column_list, axis = 1)
print(X_train.shape, Y_train.shape)
print(X_test.shape)

(246, 30) (246,)
(2, 30)

In [55]:
from sklearn.linear_model import LinearRegression

dataset1 = police12.iloc[:,3:-8]
dataset2 = new_2020.iloc[:,3:-8]

for target in column_list:
    train, test = dataset1[dataset1[target].isnull() == False], dataset2[dataset2[target].isnull()]
    X_train, Y_train = train.drop(column_list, axis = 1), train[target]
    X_test = test.drop(column_list, axis = 1)

    # 모델링
    model = LinearRegression(normalize= True)
    model.fit(X_train, Y_train)
    #model.score(X_train,Y_train)
    pred = model.predict(X_test)
    new_2020.loc[new_2020['jur_stn'] == "세종경찰서",target] = pred

In [59]:
new_2020.to_csv("new_2020.csv")

In [70]:
total = pd.concat([police12,new_2020]).sort_values(["jur_stn","year","상반기"])
total.to_csv("total.csv")